"""Cross-language parity tests.

Loads fixtures generated by scripts/generate-parity-vectors.ts (TS side)
and verifies that the Python verify() agrees with the TS @larkinsh/verify
on every case. If Python's json.dumps canonicalization ever diverges from
TypeScript's json-canonicalize on our receipt shapes, these tests go red.

Regenerate fixtures with: pnpm parity:generate
"""

from __future__ import annotations

import json
import pathlib

import pytest

from larkinsh_x402 import verify

FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def _load(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text())


def _pubkey() -> str:
    return _load("public-key.json")["publicKey"]


def test_valid_receipt_verifies():
    result = verify(_load("valid.json"), _pubkey())
    assert result["valid"] is True, f"expected valid, got {result}"
    assert result["payload"]["score"] == 62
    assert result["payload"]["wallet"] == (
        "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
    )


def test_tampered_payload_rejected():
    result = verify(_load("tampered.json"), _pubkey())
    assert result == {"valid": False, "reason": "signature mismatch"}


def test_mock_sentinel_rejected():
    result = verify(_load("mock.json"), _pubkey())
    assert result == {"valid": False, "reason": "unsigned mock receipt"}


def test_expired_receipt_rejected():
    result = verify(_load("expired.json"), _pubkey())
    assert result == {"valid": False, "reason": "expired"}


def test_extra_field_in_payload_rejected():
    # Adding any field to the payload after signing changes canonical JSON,
    # which changes the hash, which breaks the signature. Both verifiers must
    # catch this — asymmetric behavior here would be a silent forgery vector.
    result = verify(_load("extra-field.json"), _pubkey())
    assert result == {"valid": False, "reason": "signature mismatch"}


def test_fixtures_have_no_floats_or_scientific_notation():
    # Locks in the invariant that our sort_keys + compact-separators approach
    # is sufficient. If a future payload adds a float, canonicalization has to
    # escalate to a full RFC 8785 implementation on both sides.
    fixture_names = ["valid.json", "tampered.json", "mock.json", "expired.json",
                     "extra-field.json"]

    def walk(value) -> None:
        if isinstance(value, float):
            pytest.fail(f"float detected: {value!r}")
        if isinstance(value, dict):
            for v in value.values():
                walk(v)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    for name in fixture_names:
        walk(_load(name))
